all:
  children:
    control_plane:
      hosts:
        k8s-control:
          ansible_host: 192.168.100.10
    workers:
      hosts:
        k8s-worker1:
          ansible_host: 192.168.100.11
        k8s-worker2:
          ansible_host: 192.168.100.12
    hypervisor:
      hosts:
        t480:
          ansible_connection: local
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
